# Generated by Django 2.2.1 on 2019-05-13 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_portfolio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Portfolio',
        ),
    ]
